### ISSUE TITLE
INDIRECT is missing in GPUBufferUsage

### ISSUE THREAD

**Issue by beaufortfrancois** [kainino0x/-webgpu-types#2]
`INDIRECT` is missing in `GPUBufferUsage`. Can we add it as it is part of the spec? See https://gpuweb.github.io/gpuweb/#dom-gpubufferusage-indirect

@kainino0x

**Comment by kainino0x** [comment]
oops, clearly I did a bad job of one of my types updates - missed at least 2 things :)

**Comment by kainino0x** [comment]
Done in 0.0.11

**Comment by beaufortfrancois** [comment]
I thought you would programmatically generate those with some IDL to DTS library. Is this not the case?

**Comment by kainino0x** [comment]
I did autogenerate it once, but the script wasn't robust enough to use it every time. So I generated it once, fixed it up manually, then have been making the incremental changes by hand. (We don't make that many changes to the IDL so it's easy except that I miss things.)

**Comment by kainino0x** [comment]
IIRC this is the tool I used https://github.com/Microsoft/TSJS-lib-generator
